### ISSUE TITLE
有赞服务器异常返回。

### ISSUE THREAD

**Issue by chao** [Hanson/youzan-sdk#11]
在使用获得客户信息的接口的时候，如果客户不存在有赞居然不返回任何信息，只返回一个空数组。

例如：
```php
$youzan->request('youzan.scrm.customer.get', [ 'account' => '{"account_type":"Mobile", "account_id":"18xxxxxx"}'], [], '3.1.0');
```

经过调试服务器仅返回：`[]`

所以程序会出现以下提示：
```
PHP Notice:  Undefined index: response in /var/www/html/vendor/hanson/youzan-sdk/src/Api.php on line 51
```

建议，改进下Api.php对这种异常进行下捕捉。

**Comment by Hanson** [comment]
这不是一般的坑。。。。。。。

**Comment by Hanson** [comment]
正常SDK是不应该考虑接口的不正常返回的，建议先跟有赞反馈

**Comment by Hanson** [comment]
前期的话，可以暂时自行 try catch 处理

**Comment by chao** [comment]
正常的SDK确实不该处理服务器异常，这里要不你抛一个Exception出来吧。这样也方便异常的时候记录下。

![screen shot 2018-05-09 at 6 21 52 pm](https://user-images.githubusercontent.com/55872/39810007-12f33e40-53b6-11e8-8efd-ede931bb19e6.png)

**Comment by chao** [comment]
行吧，我自己处理吧。刚开始用，感觉有赞坑很多。

**Comment by Hanson** [comment]
你加微信 youzanfantuan 反馈一下吧

**Comment by chao** [comment]
Okay，谢谢啦。

**Comment by chao** [comment]
已和有赞客服沟通，技术表示会尽快修复。
