### ISSUE TITLE
参数 Token 无效 

### ISSUE THREAD

**Issue by isecret** [Hanson/youzan-sdk#13]
这个报错很奇怪，我甚至怀疑是有赞更新了接口。
报错的地址：`src/Youzan.php:57@request()` 方法，再往后就是 `src/Api.php:50` 抛出错误了。只有一个参数 Token 无效的报错。

**Comment by Hanson** [comment]
![4hko5 v2c5na_l 5 _47u](https://user-images.githubusercontent.com/10583423/40006224-6b2ef292-57cc-11e8-8c17-66217142087d.png)

有赞的问题

**Comment by isecret** [comment]
刷新了一下 Token，问题解决。

**Comment by Hanson** [comment]
👌
