### ISSUE TITLE
自用型access token需要自己维护刷新吗？

### ISSUE THREAD

**Issue by terranc** [Hanson/youzan-sdk#19]

**Comment by Hanson** [comment]
是的

**Comment by terranc** [comment]
遇到一个问题就是cache没超时，但cache里的token有赞说不可用了

**Comment by Hanson** [comment]
去有赞的群查查问题，看是 token 的问题还是缓存的问题

**Comment by terranc** [comment]
`$youzan->access_token->getToken(true)`了一下就正常了。
我现在直接每次都`new \Hanson\Youzan\Youzan`去用的接口，没有涉及token的维护，有最佳实践吗？

**Comment by Hanson** [comment]
token 等数据 数据库存起来，队列或者定时任务去更新

**Comment by terranc** [comment]
expires什么的怎么取到？只查到有getToken这么一个取当前token的方法。
是要在new Youzan之后再次去getTokenFromServer一下？

**Comment by Hanson** [comment]
建议你去 Hanson\Foundation\AbstractAccessToken 的 getToken 方法里面调试一下输出

$youzan->access_token->getToken(true) 可触发上述方法

可以打印返回值，看看是否缓存还是哪里出问题

我看了自用型是自动维护token的，需要查看一下是否缓存有问题

**Comment by terranc** [comment]
现在已经刷新了，不知道之前的token什么问题了。
现在需要处理的就是根据expires来自己维护一个刷新缓存的，也就是重新去getToken(true)的逻辑。
但expires我看new Youzan的实例里只能调用一下getTokenFromServer吗？

**Comment by Hanson** [comment]
实际上 Hanson\Foundation\AbstractAccessToken 这个类有自动处理的逻辑，在里面搜搜 cache

**Comment by terranc** [comment]
![image](https://user-images.githubusercontent.com/224353/78211273-14941700-74df-11ea-8a62-4255825cfd63.png)
我看了，不知道怎么能不再次调用getTokenFromServer，而得到这里面的expires。

**Comment by terranc** [comment]
这个问题应该不只有我这才遇到，正确姿势应该是怎样。。。
如果说需要自己维护token的过期重取逻辑，那得知道过期时间是什么时候吧。

**Comment by terranc** [comment]
而这个缓存逻辑里，是有个缓存时间的，感觉又不需要自己去维护似的。
![image](https://user-images.githubusercontent.com/224353/78211442-92f0b900-74df-11ea-8342-afcafab4c486.png)

**Comment by Hanson** [comment]
Hanson\Foundation\AbstractAccessToken 的 setToken 的参数，可以调试一下 $this->getCache()，是自动维护的

**Comment by terranc** [comment]
那其实是不需要自己维护的咯？

**Comment by Hanson** [comment]
是的
