### ISSUE TITLE
是否考虑加入 push 推送的处理？

### ISSUE THREAD

**Issue by bolechen** [Hanson/youzan-sdk#22]
出发点：
实际业务上除了主动调用 api 外，还有很多场景是需要背动处理事件的。
目前的几个项目上都是自己来处理，是否考虑在 sdk 底层提供类似的功能。参考 Easywechat 的 serve 功能。

官方文档：https://doc.youzanyun.com/doc#/content/35701/36476

如果可以的话，我会抽时间发一个 PR。

**Comment by Hanson** [comment]
文档就有消息推送呀

**Comment by bolechen** [comment]
哎，老了
