### ISSUE TITLE
composer 安装失败

### ISSUE THREAD

**Issue by wangqb** [Hanson/youzan-sdk#9]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/http-foundation (locked at v4.0.8) -> satisfiable by symfony/http-foundation[v4.0.8].
    - hanson/youzan-sdk 2.0.0 requires hanson/foundation-sdk ^1.0 -> satisfiable by hanson/foundation-sdk[1.0.0].
    - hanson/youzan-sdk 2.0.1 requires hanson/foundation-sdk ^1.0 -> satisfiable by hanson/foundation-sdk[1.0.0].
    - hanson/youzan-sdk 2.0.2 requires hanson/foundation-sdk ^1.0 -> satisfiable by hanson/foundation-sdk[1.0.0].
    - hanson/youzan-sdk 2.0.3 requires hanson/foundation-sdk ^1.0 -> satisfiable by hanson/foundation-sdk[1.0.0].
    - Conclusion: don't install hanson/foundation-sdk 1.0.0
    - Installation request for hanson/youzan-sdk ^2.0 -> satisfiable by hanson/youzan-sdk[2.0.0, 2.0.1, 2.0.2, 2.0.3].

**Comment by Hanson** [comment]
你的项目是否已经包含 symfony/http-foundation

**Comment by wangqb** [comment]
安装之后还是不行

**Comment by Hanson** [comment]
composer show symfony/http-foundation 截图看看

**Comment by wangqb** [comment]
![image](https://user-images.githubusercontent.com/15797206/38844077-82068f10-4224-11e8-93f7-af3aa24120e0.png)

**Comment by Hanson** [comment]
尝试一下 2.0.4，应该能兼容了

**Comment by wangqb** [comment]
可以了，非常感谢

**Comment by Hanson** [comment]
不客气
